# Generated by Django 3.1.2 on 2021-01-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('size', models.CharField(blank=True, max_length=2, null=True)),
                ('totalTime', models.CharField(blank=True, max_length=2, null=True)),
                ('started_timing', models.DateTimeField(auto_now_add=True)),
                ('is_booked', models.BooleanField(default=False)),
            ],
        ),
    ]
